name: fortuna
description: An application of the Hedonist philosophy.
publish_to: 'none'
version: 1.4.0
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  #time_machine: ^0.9.17
  path_provider: ^2.0.9
  share: ^2.0.4 # force change its 'compileSdkVersion' to 31 manually
  file_picker: ^4.5.1 # force change its 'compileSdkVersion' to 31 manually

flutter:
  uses-material-design: true

  #assets:
  # - assets/logo.png

  fonts:
    - family: Quattrocento
      fonts:
        - asset: assets/font/quattrocento_regular.ttf
          weight: 400
        - asset: assets/font/quattrocento_bold.ttf
          weight: 800
    - family: MorrisRoman
      fonts:
        - asset: assets/font/morris_roman_black.ttf
