name: fortuna
description: An application of the Hedonist philosophy.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  time_machine: ^0.9.17

flutter:
  uses-material-design: true

  #assets:
  # - assets/logo.png

  fonts:
    - family: Quattrocento
      fonts:
        - asset: assets/font/quattrocento_regular.ttf
          weight: 400
        - asset: assets/font/quattrocento_bold.ttf
          weight: 800
    - family: MorrisRoman
      fonts:
        - asset: assets/font/morris_roman_black.ttf
